import { ColorSchemeSelector } from "color-scheme.slint";

struct Font := {
    font_size: length,
    font_weight: float,
}

struct Typography := {
    default: Font,
}

struct Palette := {
    default: brush,
    background: brush,
    background-grey: brush,
    text: brush,
    primary: brush,
    primary_dark: brush,
    on_primary: brush,
    surface: brush,
    white: brush,
    shadow: brush,
    border: brush,
    text-tertiary: brush,
}

struct Durations := {
    fast: duration,
    medium: duration,
}

export global cupertino := {
    property <bool> dark-color-scheme: ColorSchemeSelector.dark-color-scheme;

    property <Palette> palette: {
        default: #34c759,
        background: dark-color-scheme ? #000000 : #ffffff,
        background-grey: dark-color-scheme ? #393a3e : #767680,
        text: dark-color-scheme ? #ffffff : #000000,
        primary: #007aff,
        primary_dark: #094e96,
        on_primary: #ffffff,
        surface: dark-color-scheme ? #2b2b2d : #767680,
        white: #ffffff,
        shadow: #000000,
        border: dark-color-scheme ? #545458A6 : #0000001A,
        text-tertiary: dark-color-scheme ? #EBEBF54D : #3c3c434D,
    };

    property <Typography> typo: {
        default: {
            font-size: 17px,
            font-weight: 700,
        }
    };

    property <Durations> durations: {
        fast: 150ms,
        medium: 300ms,
    };

    property <float> opacity-disabled: 0.5;
}