// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial


import { cupertino } from "cupertino.slint";

// Single line text input field with Material Design Outline TextField look and feel.
export LineEdit := Rectangle {
    property <length> font-size <=> input.font-size;
    property <string> text <=> input.text;
    property <string> placeholder-text <=> placeholder.text;
    property <bool> has-focus: input.has-focus;
    property <bool> enabled <=> input.enabled;
    property input-type <=> input.input-type;
    property horizontal-alignment <=> input.horizontal-alignment;
    property read-only <=> input.read-only;
    callback accepted <=> input.accepted;
    callback edited <=> input.edited;
   
    min-width: 120px;
  
    forward-focus: input;
    horizontal-stretch: 1;
    vertical-stretch: 0;
    min-height: max(44px, i_layout.min-height);

   
    i_layout := HorizontalLayout {  
        padding-left: 16px;
        padding-right: 16px;

        Rectangle {  
            clip: true;
            input := TextInput {
                property <length> computed_x;
                property <length> padding-outer: i_layout.padding-left + i_layout.padding-right;
    
                x: min(0px, max(parent.width - width, computed_x));
                width: max(parent.width, preferred-width);
                height: 100%;
                color: cupertino.palette.text;
                vertical-alignment: center;
                // FIXME after Roboto font can be loaded
                //font-family: md.sys.typescale.body-large.font;
                font-size: cupertino.typo.default.font-size;
                font-weight: cupertino.typo.default.font-weight;
    
                cursor-position-changed(cpos) => {
                    if (cpos.x + computed_x < padding-outer) {
                        computed_x = - cpos.x + padding-outer;
                    } else if (cpos.x + computed_x > parent.width - padding-outer) {
                        computed_x = parent.width - cpos.x - padding-outer;
                    }
                }
            }

            placeholder := Text {
                width: 100%;
                height: 100%;
                color: cupertino.palette.text-tertiary;
                font-size: cupertino.typo.default.font-size;
                font-weight: cupertino.typo.default.font-weight;
                visible: false;
                vertical-alignment: center;

                states [
                    empty when input.text == "" : {
                        visible: true;
                    }
                ]
            }
        }    
    }

    Rectangle {  
        y: parent.height - height;
        height: 1px;
        background: cupertino.palette.border;
    }

    states [
        disabled when !enabled : {
            opacity: cupertino.opacity-disabled;
        }
    ]
}